In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M',flavor = 'html5lib')
cf=pd.DataFrame(df[0])
cf.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [17]:
cf.rename({0:'Postcode',1:'Borough',2:'Neighbourhood'},axis='columns',inplace=True)
cf.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [18]:
print(cf.isnull().sum())
cf.drop(cf.index[0],inplace=True)
cf.dropna(axis=0,inplace=True)
cf.head()
print(cf.isnull().sum())
cf

Postcode         0
Borough          0
Neighbourhood    0
dtype: int64
Postcode         0
Borough          0
Neighbourhood    0
dtype: int64

,Postcode,Borough,Neighbourhood
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Harbourfront
5,M5A,Downtown Toronto,Regent Park
6,M6A,North York,Lawrence Heights
7,M6A,North York,Lawrence Manor
8,M7A,Queen's Park,Not assigned
9,M8A,Not assigned,Not assigned
10,M9A,Etobicoke,Islington Avenue
11,M1B,Scarborough,Rouge
12,M1B,Scarborough,Malvern
13,M2B,Not assigned,Not assigned
14,M3B,North York,Don Mills North
15,M4B,East York,Woodbine Gardens
16,M4B,East York,Parkview Hill
17,M5B,Downtown Toronto,Ryerson
18,M5B,Downtown Toronto,Garden District
19,M6B,North York,Glencairn
20,M7B,Not assigned,Not assigned
21,M8B,Not assigned,Not assigned
22,M9B,Etobicoke,Cloverdale
23,M9B,Etobicoke,Islington
24,M9B,Etobicoke,Martin Grove
25,M9B,Etobicoke,Princess Gardens
26,M9B,Etobicoke,West Deane Park
27,M1C,Scarborough,Highland Creek
28,M1C,Scarborough,Rouge Hill
29,M1C,Scarborough,Port Union
30,M2C,Not assigned,Not assigned
...,...,...,...
258,M9X,Not assigned,Not assigned
259,M1Y,Not assigned,Not assigned
260,M2Y,Not assigned,Not assigned
261,M3Y,Not assigned,Not assigned
262,M4Y,Downtown Toronto,Church and Wellesley
263,M5Y,Not assigned,Not assigned
264,M6Y,Not assigned,Not assigned
265,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
266,M8Y,Etobicoke,Humber Bay
267,M8Y,Etobicoke,King's Mill Park
268,M8Y,Etobicoke,Kingsway Park South East
269,M8Y,Etobicoke,Mimico NE
270,M8Y,Etobicoke,Old Mill South
271,M8Y,Etobicoke,The Queensway East
272,M8Y,Etobicoke,Royal York South East
273,M8Y,Etobicoke,Sunnylea
274,M9Y,Not assigned,Not assigned
275,M1Z,Not assigned,Not assigned
276,M2Z,Not assigned,Not assigned
277,M3Z,Not assigned,Not assigned
278,M4Z,Not assigned,Not assigned
279,M5Z,Not assigned,Not assigned
280,M6Z,Not assigned,Not assigned
281,M7Z,Not assigned,Not assigned
282,M8Z,Etobicoke,Kingsway Park South West
283,M8Z,Etobicoke,Mimico NW
284,M8Z,Etobicoke,The Queensway West
285,M8Z,Etobicoke,Royal York South West
286,M8Z,Etobicoke,South of Bloor
287,M9Z,Not assigned,Not assigned

In [24]:
print('the df has {} boroughs and {} neighbours'.format(
len(cf['Borough'].unique()),
len(cf['Neighbourhood'].unique())))

the df has 12 boroughs and 209 neighbours

In [25]:
af=pd.read_csv('/home/shubham/Downloads/Geospatial_Coordinates.csv')
af.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [28]:
af=af.sort_values(by=['Postal Code'],ascending=True)
af.reset_index(inplace=True,drop=True)
af.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [29]:
cf=cf.join(af)

In [30]:
cf.head()

,Postcode,Borough,Neighbourhood,Postal Code,Latitude,Longitude
1,M2A,Not assigned,Not assigned,M1C,43.784535,-79.160497
2,M3A,North York,Parkwoods,M1E,43.763573,-79.188711
3,M4A,North York,Victoria Village,M1G,43.770992,-79.216917
4,M5A,Downtown Toronto,Harbourfront,M1H,43.773136,-79.239476
5,M5A,Downtown Toronto,Regent Park,M1J,43.744734,-79.239476

In [31]:
cf.shape

(287, 6)

In [32]:
import folium
from geopy.geocoders import Nominatim

In [33]:
import json
from pandas.io.json import json_normalize

In [34]:
new_cf=cf[cf.Borough.str.contains('Toronto')]

In [35]:
new_cf.shape

(74, 6)

In [38]:
new_cf.head(10)

,Postcode,Borough,Neighbourhood,Postal Code,Latitude,Longitude
4,M5A,Downtown Toronto,Harbourfront,M1H,43.773136,-79.239476
5,M5A,Downtown Toronto,Regent Park,M1J,43.744734,-79.239476
17,M5B,Downtown Toronto,Ryerson,M2H,43.803762,-79.363452
18,M5B,Downtown Toronto,Garden District,M2J,43.778517,-79.346556
34,M5C,Downtown Toronto,St. James Town,M4A,43.725882,-79.315572
47,M4E,East Toronto,The Beaches,M4S,43.704324,-79.388790
48,M5E,Downtown Toronto,Berczy Park,M4T,43.689574,-79.383160
57,M5G,Downtown Toronto,Central Bay Street,M5G,43.657952,-79.387383
58,M6G,Downtown Toronto,Christie,M5H,43.650571,-79.384568
68,M5H,Downtown Toronto,Adelaide,M5V,43.628947,-79.394420

In [40]:
print('Borough',len(new_cf.Borough.value_counts()))
print('Postcode',len(new_cf.Postcode.value_counts()))

Borough 4
Postcode 38

In [47]:
new_cf.shape

(74, 6)

In [54]:
address = 'Toronto, Ontario, Canada'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Toronto are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Toronto are 43.653963, -79.387207.

In [ ]:
map_toronto = folium.Map(location=[latitude, longitude], zoom_start=11)
for lat,lng,label in zip(new_cf['Latitude'],new_cf['Longitude'],new_cf['Neighbourhood']):
    label=folium.Popup(label,parse_html=True)
    folium.CircleMarker(
    [lat,lng],
    radius=5,
    popup=label,
    color='red',
    fill=True,
    fill_color='#3186cc',
    fill_opacity=0.7,
    parse_html=False
    ).add_to(map_toronto)